Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.define "docker" do |dm|
   dm.vm.hostname = "dockermaster"
   dm.vm.network "private_network", ip: "192.168.50.10"
   dm.vm.provision "shell", path: "installdocker.sh"
   dm.vm.provider "virtualbox" do |vb|
      vb.name = "dock-master"    
      vb.memory = "2048"
      vb.cpus = "2"
   end
  end

(1..2).each do |i|
    config.vm.define "swarm-node-#{i}" do |d|
      d.vm.box = "centos/7"
      d.vm.network "private_network", ip: "192.168.50.1#{i}"
      d.vm.hostname = "swarm-node-#{i}"
      d.vm.provision :"shell", path: "installdocker.sh"
       d.vm.provider "virtualbox" do |v|
        v.memory = "1096"
        v.cpus = "1"
       end
     end
end

end

