Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "jenkins"
  config.vm.network "forwarded_port", guest: 8080, host: 8081
  config.vm.provision "shell", path: "installjenkins.sh"
  config.vm.provider "virtualbox" do |vb|
  vb.memory = "2048"
  vb.name = "centos-jenkins"
  vb.cpus = "2"
  end
end
